Resources:
  StartStopRDSPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: StartStopRDSPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - rds:DescribeDBInstances
          - rds:StopDBInstance
          - rds:StartDBInstance
          Resource: '*'
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource: '*'

  StartStopRDsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StartStopRDSRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: 
        - !Ref StartStopRDSPolicy

  StopRDSFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: StopRDSFunction
      Code:
        ZipFile: |
          import os
          import boto3
          def handler (event, context):
            rds = boto3.client('rds')
            DBinstance = os.environ['dbInstanceName']
            response = rds.stop_db_instance(DBInstanceIdentifier=DBinstance)
            return 'LAMBDA executou com sucesso'
      Handler: index.handler
      Runtime: python3.8
      Role: !GetAtt StartStopRDsRole.Arn
      Environment:
        Variables:
          dbInstanceName : first-rds

  StartRDSFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: StartRDSFunction
      Code:
        ZipFile: |
          import os
          import boto3
          def handler (event, context):
            rds = boto3.client('rds')
            DBinstance = os.environ['dbInstanceName']
            response = rds.start_db_instance(DBInstanceIdentifier=DBinstance)
            return 'LAMBDA executou com sucesso'
      Handler: index.handler
      Runtime: python3.8
      Role: !GetAtt StartStopRDsRole.Arn
      Environment:
        Variables:
          dbInstanceName : first-rds

  StopRDSEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: StopRDSEventRule
      Description: Rule to stop RDS after commercial hours
      ScheduleExpression: 'cron(0 21 ? * MON-FRI *)'
      Targets:
        - Arn: !GetAtt StopRDSFunction.Arn
          Id: StopRDSFunction

  StartRDSEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: StartRDSEventRule
      Description: Rule to start RDS before commercial hours
      ScheduleExpression: 'cron(0 12 ? * MON-FRI *)'
      Targets:
        - Arn: !GetAtt StartRDSFunction.Arn
          Id: StartRDSFunction